---
services:
  postgres:
    image: postgres:14-alpine
    volumes:
      - postgresql:/var/lib/postgresql/data:delegated
      - ./docker-postgres-init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      CURRENT_USER: ${USER}
      POSTGRES_HOST_AUTH_METHOD: trust
volumes:
  postgresql:
  storage:
